"""
Order routing logic.
Compares model probability against the live Polymarket CLOB
to identify mispricings and construct post-only GTD limit orders.
"""

import logging
import math
import time
from dataclasses import dataclass, replace
from typing import Optional

from config.settings import TRADING
from src.exchange.gamma_api import GammaAPIClient, MarketInfo
from src.exchange.polymarket_client import OrderResult, PolymarketClient

logger = logging.getLogger(__name__)


def _get_bool_setting(name: str, default: bool) -> bool:
    """Read an optional boolean from TRADING config."""
    return bool(getattr(TRADING, name, default))


def _get_float_setting(name: str, default: float) -> float:
    """Read an optional float from TRADING config."""
    try:
        return float(getattr(TRADING, name, default))
    except (TypeError, ValueError):
        return default


def _get_int_setting(name: str, default: int) -> int:
    """Read an optional int from TRADING config."""
    try:
        return int(getattr(TRADING, name, default))
    except (TypeError, ValueError):
        return default


@dataclass
class TradingSignal:
    """A trade signal generated by comparing model output to market prices."""
    side: str           # "BUY_YES" or "BUY_NO"
    token_id: str       # Which token to buy
    price: float        # Limit price to place
    size: float         # Number of shares
    edge: float         # Model edge over market price
    model_prob: float   # Model's predicted probability
    market_price: float # Current market price
    timestamp: float    # When signal was generated


@dataclass
class OrderSizingDecision:
    """Resolved order sizing after venue minimums and bankroll caps."""
    allowed: bool
    size: float
    required_collateral: float
    reason: Optional[str] = None
    available_collateral: Optional[float] = None
    min_order_size: Optional[float] = None


@dataclass
class OrderBookSnapshot:
    """Compact order book summary used for quality filters."""
    best_bid: Optional[float]
    best_ask: Optional[float]
    bid_size_total: float
    ask_size_total: float

    @property
    def imbalance(self) -> Optional[float]:
        total = self.bid_size_total + self.ask_size_total
        if total <= 0:
            return None
        return self.bid_size_total / total

    @property
    def ask_wall_ratio(self) -> Optional[float]:
        if self.bid_size_total <= 0:
            return None
        return self.ask_size_total / self.bid_size_total


class OrderRouter:
    """
    Compares the model's probability prediction against live Polymarket CLOB prices.
    Identifies mispricings and routes post-only GTD limit orders.
    """

    def __init__(
        self,
        client: PolymarketClient,
        min_edge: Optional[float] = None,
        order_size: Optional[float] = None,
        order_notional: Optional[float] = None,
        gtd_ttl: Optional[int] = None,
        dry_run: Optional[bool] = None,
        min_side_probability: Optional[float] = None,
        duplicate_window_seconds: Optional[int] = None,
        bankroll_fraction_per_order: Optional[float] = None,
        max_order_notional: Optional[float] = None,
        reserve_collateral_amount: Optional[float] = None,
        allow_upsize_to_min_order_size: Optional[bool] = None,
        order_book_imbalance_levels: Optional[int] = None,
        min_order_book_imbalance: Optional[float] = None,
        max_ask_wall_ratio: Optional[float] = None,
        max_entry_price: Optional[float] = None,
        use_kelly_sizing: Optional[bool] = None,
        kelly_fraction: Optional[float] = None,
        min_time_remaining_seconds: Optional[int] = None,
        use_bid_side_entry: Optional[bool] = None,
    ):
        self._client = client
        self._min_edge = min_edge if min_edge is not None else TRADING.min_edge
        self._min_side_probability = (
            min_side_probability
            if min_side_probability is not None
            else getattr(TRADING, "min_side_probability", 0.52)
        )
        self._max_entry_price = (
            max_entry_price
            if max_entry_price is not None
            else getattr(TRADING, "max_entry_price", 0.90)
        )
        self._order_size = (
            order_size if order_size is not None else TRADING.order_size
        )
        if order_notional is not None:
            self._order_notional = order_notional
        elif order_size is not None:
            # Respect explicit share sizing even when the environment configures
            # a default dollar budget for the main app.
            self._order_notional = 0.0
        else:
            self._order_notional = TRADING.order_notional
        self._gtd_ttl = gtd_ttl if gtd_ttl is not None else TRADING.gtd_ttl_seconds
        self._dry_run = dry_run if dry_run is not None else TRADING.dry_run
        self._duplicate_window_seconds = (
            duplicate_window_seconds
            if duplicate_window_seconds is not None
            else TRADING.duplicate_signal_window_seconds
        )
        self._bankroll_fraction_per_order = (
            bankroll_fraction_per_order
            if bankroll_fraction_per_order is not None
            else TRADING.bankroll_fraction_per_order
        )
        self._max_order_notional = (
            max_order_notional
            if max_order_notional is not None
            else TRADING.max_order_notional
        )
        self._reserve_collateral_amount = (
            reserve_collateral_amount
            if reserve_collateral_amount is not None
            else TRADING.reserve_collateral_amount
        )
        self._allow_upsize_to_min_order_size = (
            allow_upsize_to_min_order_size
            if allow_upsize_to_min_order_size is not None
            else TRADING.allow_upsize_to_min_order_size
        )
        self._order_book_imbalance_levels = (
            order_book_imbalance_levels
            if order_book_imbalance_levels is not None
            else getattr(TRADING, "order_book_imbalance_levels", 5)
        )
        self._min_order_book_imbalance = (
            min_order_book_imbalance
            if min_order_book_imbalance is not None
            else getattr(TRADING, "min_order_book_imbalance", 0.35)
        )
        self._max_ask_wall_ratio = (
            max_ask_wall_ratio
            if max_ask_wall_ratio is not None
            else getattr(TRADING, "max_ask_wall_ratio", 2.5)
        )
        self._use_kelly_sizing = (
            use_kelly_sizing
            if use_kelly_sizing is not None
            else _get_bool_setting("use_kelly_sizing", False)
        )
        self._kelly_fraction = (
            kelly_fraction
            if kelly_fraction is not None
            else _get_float_setting("kelly_fraction", 0.25)
        )
        self._min_time_remaining_seconds = (
            min_time_remaining_seconds
            if min_time_remaining_seconds is not None
            else _get_int_setting("min_time_remaining_seconds", 60)
        )
        self._use_bid_side_entry = (
            use_bid_side_entry
            if use_bid_side_entry is not None
            else _get_bool_setting("use_bid_side_entry", True)
        )
        self._orders_placed = 0
        self._orders_rejected = 0
        self._orders_simulated = 0
        self._duplicate_signals_suppressed = 0
        self._recent_signal_times: dict[str, float] = {}

    @property
    def orders_placed(self) -> int:
        return self._orders_placed

    @property
    def orders_rejected(self) -> int:
        return self._orders_rejected

    @property
    def orders_simulated(self) -> int:
        return self._orders_simulated

    @property
    def duplicate_signals_suppressed(self) -> int:
        return self._duplicate_signals_suppressed

    def evaluate_and_trade(
        self,
        model_prob: float,
        market: MarketInfo,
    ) -> Optional[OrderResult]:
        """
        Core trading decision loop:
        
        1. Fetch best bid/ask from CLOB for both YES and NO tokens
        2. Compare model probability against market prices
        3. If edge > min_edge, place a post-only GTD limit order
        4. Return the order result
        
        Args:
            model_prob: p̂ᵢ — model's probability that BTC goes up
            market: Active MarketInfo with token IDs
            
        Returns:
            OrderResult if an order was placed, None if no edge found.
        """
        signal = self.get_signal(model_prob, market)
        if signal is None:
            return None

        return self.execute_signal(signal, market)

    def get_signal(
        self,
        model_prob: float,
        market: MarketInfo,
    ) -> Optional[TradingSignal]:
        """Return a tradeable signal for the current market, if one exists."""
        yes_book = self._safe_get_order_book(market.yes_token_id)
        no_book = self._safe_get_order_book(market.no_token_id)
        yes_book_snapshot = self._summarize_order_book(yes_book)
        no_book_snapshot = self._summarize_order_book(no_book)

        yes_bid = yes_book_snapshot.best_bid if yes_book_snapshot else None
        yes_ask = yes_book_snapshot.best_ask if yes_book_snapshot else None
        no_bid = no_book_snapshot.best_bid if no_book_snapshot else None
        no_ask = no_book_snapshot.best_ask if no_book_snapshot else None
        if yes_bid is None and yes_ask is None:
            yes_bid, yes_ask = self._client.get_best_bid_ask(market.yes_token_id)
        if no_bid is None and no_ask is None:
            no_bid, no_ask = self._client.get_best_bid_ask(market.no_token_id)

        yes_ask = self._select_dry_run_reference_price(
            live_bid=yes_bid,
            live_price=yes_ask,
            indicative_price=market.indicative_yes_price,
        )
        no_ask = self._select_dry_run_reference_price(
            live_bid=no_bid,
            live_price=no_ask,
            indicative_price=market.indicative_no_price,
        )
        return self._find_signal(
            model_prob,
            market,
            yes_bid,
            yes_ask,
            no_bid,
            no_ask,
            yes_book_snapshot,
            no_book_snapshot,
        )

    def execute_signal(
        self,
        signal: TradingSignal,
        market: MarketInfo,
    ) -> OrderResult:
        """Execute or simulate a previously identified signal."""
        logger.info(
            "Signal found | side=%s edge=%.4f model_p=%.4f market_p=%.4f price=%.2f size=%.4f",
            signal.side,
            signal.edge,
            signal.model_prob,
            signal.market_price,
            signal.price,
            signal.size,
        )

        signal_key = self._build_signal_key(market, signal)
        if self._is_duplicate_signal(signal_key, signal.timestamp):
            self._duplicate_signals_suppressed += 1
            logger.info(
                "Duplicate signal suppressed | market=%s side=%s window=%ds count=%d",
                market.slug or market.condition_id,
                signal.side,
                self._duplicate_window_seconds,
                self._duplicate_signals_suppressed,
            )
            return OrderResult(
                success=False,
                error="duplicate_signal_suppressed",
                raw_response={
                    "reason": "duplicate_signal_suppressed",
                    "market": market.slug or market.condition_id,
                    "side": signal.side,
                    "duplicate_window_seconds": self._duplicate_window_seconds,
                },
            )

        self._remember_signal(signal_key, signal.timestamp)

        sizing = self._resolve_order_size(signal, market)
        if not sizing.allowed:
            if self._dry_run:
                self._orders_simulated += 1
                logger.warning(
                    "Dry-run signal simulated despite live sizing block | reason=%s "
                    "side=%s price=%.2f size=%.4f #%d",
                    sizing.reason,
                    signal.side,
                    signal.price,
                    signal.size,
                    self._orders_simulated,
                )
                return OrderResult(
                    success=True,
                    order_id=f"dry-run:{market.condition_id}:{signal.side}",
                    raw_response={
                        "dry_run": True,
                        "market": market.slug,
                        "side": signal.side,
                        "price": signal.price,
                        "size": signal.size,
                        "live_blocked": True,
                        "live_block_reason": sizing.reason,
                        "min_order_size": sizing.min_order_size,
                        "available_collateral": sizing.available_collateral,
                    },
                )

            self._orders_rejected += 1
            logger.warning(
                "Order blocked by sizing guard | reason=%s side=%s price=%.2f requested=%.4f "
                "market_min=%s available_collateral=%s #%d",
                sizing.reason,
                signal.side,
                signal.price,
                signal.size,
                (
                    f"{sizing.min_order_size:.4f}"
                    if sizing.min_order_size is not None
                    else "N/A"
                ),
                (
                    f"{sizing.available_collateral:.4f}"
                    if sizing.available_collateral is not None
                    else "N/A"
                ),
                self._orders_rejected,
            )
            return OrderResult(
                success=False,
                error=sizing.reason,
                raw_response={
                    "reason": "order_sizing_blocked",
                    "detail": sizing.reason,
                    "market": market.slug,
                    "side": signal.side,
                    "price": signal.price,
                    "requested_size": signal.size,
                    "resolved_size": sizing.size,
                    "min_order_size": sizing.min_order_size,
                    "available_collateral": sizing.available_collateral,
                },
            )

        if abs(sizing.size - signal.size) > 1e-9:
            logger.info(
                "Adjusted order size | side=%s requested=%.4f resolved=%.4f "
                "required_collateral=%.4f",
                signal.side,
                signal.size,
                sizing.size,
                sizing.required_collateral,
            )
            signal = replace(signal, size=sizing.size)

        if self._dry_run:
            self._orders_simulated += 1
            logger.info(
                "Dry-run order simulated | market=%s side=%s price=%.2f size=%.4f #%d",
                market.slug or market.condition_id,
                signal.side,
                signal.price,
                signal.size,
                self._orders_simulated,
            )
            return OrderResult(
                success=True,
                order_id=f"dry-run:{market.condition_id}:{signal.side}",
                raw_response={
                    "dry_run": True,
                    "market": market.slug,
                    "side": signal.side,
                    "price": signal.price,
                    "size": signal.size,
                    "live_blocked": False,
                },
            )

        if not self._client.has_sufficient_collateral(sizing.required_collateral):
            self._orders_rejected += 1
            logger.warning(
                "Order blocked by collateral guard | required=%.4f side=%s price=%.2f "
                "size=%.2f #%d",
                sizing.required_collateral,
                signal.side,
                signal.price,
                signal.size,
                self._orders_rejected,
            )
            return OrderResult(
                success=False,
                error="Insufficient balance or allowance",
                raw_response={
                    "reason": "insufficient_balance_or_allowance",
                    "required_collateral": sizing.required_collateral,
                    "market": market.slug,
                    "side": signal.side,
                    "price": signal.price,
                    "size": signal.size,
                },
            )

        # Execute the trade
        result = self._client.place_post_only_gtd(
            token_id=signal.token_id,
            price=signal.price,
            size=signal.size,
            side="BUY",
            ttl_seconds=self._gtd_ttl,
            neg_risk=market.neg_risk,
        )

        if result.success:
            self._orders_placed += 1
            logger.info(
                "Order executed | id=%s side=%s price=%.2f #%d",
                result.order_id, signal.side, signal.price, self._orders_placed,
            )
        else:
            self._orders_rejected += 1
            logger.warning(
                "Order rejected | error=%s side=%s price=%.2f #%d",
                result.error, signal.side, signal.price, self._orders_rejected,
            )

        return result

    def _resolve_order_size(
        self,
        signal: TradingSignal,
        market: MarketInfo,
    ) -> OrderSizingDecision:
        """Apply venue minimums plus bankroll/notional caps to a signal size."""
        if signal.price <= 0:
            return OrderSizingDecision(
                allowed=False,
                size=0.0,
                required_collateral=0.0,
                reason="Invalid order price",
                min_order_size=market.min_order_size,
            )

        if signal.size <= 0:
            return OrderSizingDecision(
                allowed=False,
                size=0.0,
                required_collateral=0.0,
                reason="Configured order size must be positive",
                min_order_size=market.min_order_size,
            )

        min_order_size = market.min_order_size
        resolved_size = signal.size

        if min_order_size is not None and resolved_size + 1e-9 < min_order_size:
            if not self._allow_upsize_to_min_order_size:
                return OrderSizingDecision(
                    allowed=False,
                    size=resolved_size,
                    required_collateral=signal.price * resolved_size,
                    reason=(
                        "Configured order size is below the market minimum size"
                    ),
                    min_order_size=min_order_size,
                )
            resolved_size = min_order_size

        available_collateral = self._client.get_available_collateral()
        spend_cap = self._resolve_spend_cap(signal.price, available_collateral)
        if spend_cap is not None:
            if spend_cap <= 0:
                return OrderSizingDecision(
                    allowed=False,
                    size=0.0,
                    required_collateral=0.0,
                    reason="No spendable collateral available",
                    available_collateral=available_collateral,
                    min_order_size=min_order_size,
                )

            max_affordable_size = spend_cap / signal.price
            if max_affordable_size + 1e-9 < resolved_size:
                resolved_size = max_affordable_size

            if min_order_size is not None and resolved_size + 1e-9 < min_order_size:
                return OrderSizingDecision(
                    allowed=False,
                    size=max(resolved_size, 0.0),
                    required_collateral=max(resolved_size, 0.0) * signal.price,
                    reason="Available collateral cannot fund the market minimum size",
                    available_collateral=available_collateral,
                    min_order_size=min_order_size,
                )

        resolved_size = max(resolved_size, 0.0)
        required_collateral = resolved_size * signal.price
        if required_collateral <= 0:
            return OrderSizingDecision(
                allowed=False,
                size=0.0,
                required_collateral=0.0,
                reason="Resolved order size must be positive",
                available_collateral=available_collateral,
                min_order_size=min_order_size,
            )

        return OrderSizingDecision(
            allowed=True,
            size=resolved_size,
            required_collateral=required_collateral,
            available_collateral=available_collateral,
            min_order_size=min_order_size,
        )

    def _resolve_spend_cap(
        self,
        price: float,
        available_collateral: Optional[float],
    ) -> Optional[float]:
        """Return the maximum collateral this order may consume, if capped."""
        if price <= 0:
            return 0.0

        spend_cap: Optional[float] = None
        if available_collateral is not None:
            spendable_collateral = max(
                available_collateral - self._reserve_collateral_amount,
                0.0,
            )
            bankroll_fraction = min(max(self._bankroll_fraction_per_order, 0.0), 1.0)
            spend_cap = spendable_collateral * bankroll_fraction

        if self._max_order_notional > 0:
            if spend_cap is None:
                spend_cap = self._max_order_notional
            else:
                spend_cap = min(spend_cap, self._max_order_notional)

        return spend_cap

    def _build_signal_key(self, market: MarketInfo, signal: TradingSignal) -> str:
        """Build a stable deduplication key for a market-side signal."""
        return f"{market.condition_id}:{signal.side}"

    def _is_duplicate_signal(self, signal_key: str, now: float) -> bool:
        """
        Return True when a similar signal fired too recently.
        Also performs periodic cleanup of the signal cache.
        """
        # Periodic cleanup (every 100 checks)
        if self._orders_placed % 100 == 0:
            self._cleanup_stale_signals(now)

        last_seen = self._recent_signal_times.get(signal_key)
        if last_seen is None:
            return False
        return (now - last_seen) < self._duplicate_window_seconds

    def _cleanup_stale_signals(self, now: float):
        """Remove signals older than the duplicate window to prevent memory leaks."""
        stale_threshold = self._duplicate_window_seconds * 2
        stale_keys = [
            k for k, t in self._recent_signal_times.items() 
            if (now - t) > stale_threshold
        ]
        for k in stale_keys:
            del self._recent_signal_times[k]

    def _remember_signal(self, signal_key: str, now: float):
        """Persist the signal timestamp for duplicate suppression."""
        self._recent_signal_times[signal_key] = now

    def _resolve_signal_size(
        self, price: float, model_prob: Optional[float] = None
    ) -> float:
        """
        Resolve the initial signal size in shares.

        When `ORDER_NOTIONAL` is set, it takes precedence over `ORDER_SIZE` so
        a small bankroll can target a strict dollar spend per trade.

        Improvement 6: When Kelly sizing is enabled, scale the base size by
        fractional Kelly criterion based on model confidence.
        """
        if price <= 0:
            return 0.0

        if self._order_notional > 0:
            base_size = self._order_notional / price
        else:
            base_size = self._order_size

        # Apply fractional Kelly scaling when enabled
        if self._use_kelly_sizing and model_prob is not None and price > 0:
            kelly_size = self._kelly_optimal_fraction(model_prob, price)
            if kelly_size is not None:
                base_size = base_size * kelly_size

        return max(base_size, 0.0)

    def _find_signal(
        self,
        model_prob: float,
        market: MarketInfo,
        yes_bid: Optional[float],
        yes_ask: Optional[float],
        no_bid: Optional[float],
        no_ask: Optional[float],
        yes_book_snapshot: Optional[OrderBookSnapshot] = None,
        no_book_snapshot: Optional[OrderBookSnapshot] = None,
    ) -> Optional[TradingSignal]:
        """
        Check if the model's probability creates a tradeable edge.

        Strategy:
        - If model thinks YES is underpriced (p̂ > best_ask_yes + min_edge):
          → BUY YES at best_bid_yes + 1 tick (or ask, depending on config)
        - If model thinks NO is underpriced ((1-p̂) > best_ask_no + min_edge):
          → BUY NO at best_bid_no + 1 tick
        """
        now = time.time()

        # Improvement 4: Don't enter near market expiry
        if not self._has_sufficient_time_remaining(market):
            return None

        # --- Check YES side ---
        if yes_ask is not None and yes_ask > 0:
            # Improvement 1 + 5: dynamic edge scaling
            effective_edge = self._compute_effective_min_edge(model_prob)
            yes_edge = model_prob - yes_ask
            if yes_edge >= effective_edge and model_prob >= self._min_side_probability:
                if self._passes_order_book_filters(
                    market,
                    "BUY_YES",
                    yes_book_snapshot,
                ):
                    # Improvement 7: bid-side entry for price improvement
                    limit_price = self._compute_entry_price(
                        yes_bid, yes_ask, "BUY_YES"
                    )
                    if self._passes_entry_price_filter(
                        market,
                        "BUY_YES",
                        limit_price,
                    ):
                        # Improvement 6: Kelly sizing
                        size = self._resolve_signal_size(
                            limit_price, model_prob=model_prob
                        )
                        return TradingSignal(
                            side="BUY_YES",
                            token_id=market.yes_token_id,
                            price=limit_price,
                            size=size,
                            edge=yes_edge,
                            model_prob=model_prob,
                            market_price=yes_ask,
                            timestamp=now,
                        )

        # --- Check NO side ---
        no_model_prob = 1.0 - model_prob
        if no_ask is not None and no_ask > 0:
            effective_edge = self._compute_effective_min_edge(no_model_prob)
            no_edge = no_model_prob - no_ask
            if no_edge >= effective_edge and no_model_prob >= self._min_side_probability:
                if self._passes_order_book_filters(
                    market,
                    "BUY_NO",
                    no_book_snapshot,
                ):
                    limit_price = self._compute_entry_price(
                        no_bid, no_ask, "BUY_NO"
                    )
                    if self._passes_entry_price_filter(
                        market,
                        "BUY_NO",
                        limit_price,
                    ):
                        size = self._resolve_signal_size(
                            limit_price, model_prob=no_model_prob
                        )
                        return TradingSignal(
                            side="BUY_NO",
                            token_id=market.no_token_id,
                            price=limit_price,
                            size=size,
                            edge=no_edge,
                            model_prob=no_model_prob,
                            market_price=no_ask,
                            timestamp=now,
                        )

        return None

    def _passes_order_book_filters(
        self,
        market: MarketInfo,
        side: str,
        snapshot: Optional[OrderBookSnapshot],
    ) -> bool:
        """Reject entries facing obvious order-book resistance.

        Bug 2 fix: for BUY_YES, high bid imbalance = buy pressure = favorable.
        For BUY_NO, high bid imbalance on the NO book means NO-side buy pressure,
        which is also favorable for a BUY_NO entry.  The imbalance filter should
        check whether the side we want to BUY has sufficient buying interest
        (our order adds to bid-side liquidity).  A low imbalance means the ask
        side dominates — unfavorable for a maker buy.
        """
        if snapshot is None:
            return True

        imbalance = snapshot.imbalance
        if imbalance is not None:
            # imbalance = bid_total / (bid_total + ask_total)
            # High imbalance = lots of bids = buy pressure = good for our buy
            # Low imbalance = ask-heavy book = sell pressure = bad for our buy
            if imbalance < self._min_order_book_imbalance:
                logger.info(
                    "Signal filtered by book imbalance | market=%s side=%s "
                    "imbalance=%.4f min=%.4f",
                    market.slug or market.condition_id,
                    side,
                    imbalance,
                    self._min_order_book_imbalance,
                )
                return False

        ask_wall_ratio = snapshot.ask_wall_ratio
        if (
            ask_wall_ratio is not None
            and ask_wall_ratio > self._max_ask_wall_ratio
        ):
            logger.info(
                "Signal filtered by ask wall | market=%s side=%s "
                "ask_wall_ratio=%.4f max=%.4f",
                market.slug or market.condition_id,
                side,
                ask_wall_ratio,
                self._max_ask_wall_ratio,
            )
            return False

        return True

    def _passes_entry_price_filter(
        self,
        market: MarketInfo,
        side: str,
        price: float,
    ) -> bool:
        """Reject entries that are too expensive relative to capped upside."""
        if self._max_entry_price <= 0 or self._max_entry_price >= 1:
            return True

        if price <= self._max_entry_price + 1e-9:
            return True

        logger.info(
            "Signal filtered by max entry price | market=%s side=%s "
            "price=%.4f max_entry_price=%.4f",
            market.slug or market.condition_id,
            side,
            price,
            self._max_entry_price,
        )
        return False

    def _safe_get_order_book(self, token_id: str):
        """Fetch a raw order book snapshot when the client can provide one."""
        get_order_book = getattr(self._client, "get_order_book", None)
        if not callable(get_order_book):
            return None
        try:
            return get_order_book(token_id)
        except Exception:
            return None

    def _summarize_order_book(self, book) -> Optional[OrderBookSnapshot]:
        """Summarize the top levels of a book into imbalance metrics."""
        if book is None:
            return None

        bids, asks = self._extract_book_levels(book)
        if bids is None or asks is None:
            return None

        bid_levels = bids[: self._order_book_imbalance_levels]
        ask_levels = asks[: self._order_book_imbalance_levels]
        best_bid = self._best_price(bid_levels, max)
        best_ask = self._best_price(ask_levels, min)

        return OrderBookSnapshot(
            best_bid=best_bid,
            best_ask=best_ask,
            bid_size_total=sum(self._level_size(level) for level in bid_levels),
            ask_size_total=sum(self._level_size(level) for level in ask_levels),
        )

    @staticmethod
    def _extract_book_levels(book) -> tuple[Optional[list], Optional[list]]:
        if isinstance(book, dict):
            bids = book.get("bids")
            asks = book.get("asks")
            if isinstance(bids, list) and isinstance(asks, list):
                return bids, asks
            return None, None

        bids = getattr(book, "bids", None)
        asks = getattr(book, "asks", None)
        if isinstance(bids, list) and isinstance(asks, list):
            return bids, asks
        return None, None

    @staticmethod
    def _best_price(levels: list, selector) -> Optional[float]:
        prices = [OrderRouter._level_price(level) for level in levels]
        prices = [price for price in prices if price is not None and price > 0]
        if not prices:
            return None
        return selector(prices)

    @staticmethod
    def _level_price(level) -> Optional[float]:
        raw_price = level.get("price") if isinstance(level, dict) else getattr(level, "price", None)
        try:
            return float(raw_price)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _level_size(level) -> float:
        raw_size = (
            level.get("size", level.get("quantity", 0.0))
            if isinstance(level, dict)
            else getattr(level, "size", getattr(level, "quantity", 0.0))
        )
        try:
            return max(float(raw_size), 0.0)
        except (TypeError, ValueError):
            return 0.0

    @staticmethod
    def _snap_price(price: float) -> float:
        """
        Snap a price to the Polymarket tick size (0.01).
        Rounds down to nearest tick for post-only compliance.

        Bug 1 fix: previously subtracted an extra tick after snapping,
        costing ~2% edge per trade on a 50¢ market.
        """
        tick = float(TRADING.tick_size)
        # Round down to nearest tick — this alone ensures post-only
        snapped = int(price / tick) * tick
        return max(round(snapped, 2), 0.01)

    def _compute_entry_price(
        self,
        best_bid: Optional[float],
        best_ask: Optional[float],
        side: str,
    ) -> float:
        """
        Improvement 7: Compute the entry limit price.

        When bid-side entry is enabled, place at best_bid + 1 tick instead
        of snapping down from the ask. This provides price improvement on
        every fill while still sitting on the maker side of the book.
        """
        tick = float(TRADING.tick_size)

        if (
            self._use_bid_side_entry
            and best_bid is not None
            and best_bid > 0
            and best_ask is not None
            and best_ask > 0
        ):
            spread = best_ask - best_bid
            if spread > tick + 1e-9:
                # Place at best_bid + 1 tick (inside the spread)
                entry = best_bid + tick
                return max(round(entry, 2), 0.01)

        # Fallback: snap to the ask
        if best_ask is not None and best_ask > 0:
            return self._snap_price(best_ask)
        if best_bid is not None and best_bid > 0:
            return self._snap_price(best_bid)
        return 0.01

    def _compute_effective_min_edge(self, model_prob: float) -> float:
        """
        Improvement 1 + 5: Dynamic minimum edge.

        Scales higher when the model is near certainty (less room for error)
        and stays at base level for balanced predictions.
        """
        # Confidence scaling: require more edge near the boundaries
        confidence_penalty = 2.0 * abs(model_prob - 0.5)
        return self._min_edge * (1.0 + confidence_penalty)

    def _has_sufficient_time_remaining(self, market: MarketInfo) -> bool:
        """
        Improvement 4: Don't enter positions near market expiry.

        Late entries have less time for the underlying to move, but the same
        binary payout risk. Near expiry, market prices converge to true
        probability, leaving no exploitable edge.
        """
        if self._min_time_remaining_seconds <= 0:
            return True

        end_ts = GammaAPIClient._parse_iso_timestamp(market.end_date)
        if end_ts is None:
            return True

        time_remaining = end_ts - time.time()
        if time_remaining < self._min_time_remaining_seconds:
            logger.debug(
                "Skipping entry — too close to expiry | market=%s "
                "remaining=%.0fs min=%ds",
                market.slug or market.condition_id,
                time_remaining,
                self._min_time_remaining_seconds,
            )
            return False
        return True

    def _kelly_optimal_fraction(
        self, model_prob: float, entry_price: float
    ) -> Optional[float]:
        """
        Improvement 6: Fractional Kelly criterion sizing.

        f* = (p * b - q) / b
        where p = win probability, q = 1-p, b = net payout odds.
        Capped at `kelly_fraction` (default 25%) for safety.
        """
        if entry_price <= 0 or entry_price >= 1:
            return None

        # Binary market payout: pay `entry_price`, receive 1.0 on win
        b = (1.0 - entry_price) / entry_price  # net payout odds
        p = model_prob
        q = 1.0 - p

        if b <= 0:
            return None

        kelly_f = (p * b - q) / b
        if kelly_f <= 0:
            return 0.0  # Negative Kelly means don't bet

        # Apply fractional Kelly cap
        return min(kelly_f, self._kelly_fraction)

    def _select_dry_run_reference_price(
        self,
        live_bid: Optional[float],
        live_price: Optional[float],
        indicative_price: Optional[float],
    ) -> Optional[float]:
        """
        In dry-run mode only, fall back to indicative market pricing when the
        live book is missing or clearly unusable for paper validation.
        """
        if not self._dry_run:
            return live_price

        if indicative_price is None or indicative_price <= 0:
            return live_price

        if live_price is None or live_price <= 0:
            return indicative_price

        if live_bid is None or live_bid <= 0:
            return live_price

        if (live_price - live_bid) >= 0.20:
            return indicative_price

        return live_price
